import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>onarma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/imagem/reciclagem.png" />
      </Head>

      <main className={styles.main}>

      <video  autoPlay muted loop className={styles.videofundo} > 
                 
                 <source src={"/imagem/mundo.mp4" }type="video/mp4"/>       
             </video>
        <h1 className={styles.title}>
          Onarma <a href="https://nextjs.org"></a>
        </h1>

        <p>organizaçao nao governamental amigos do rio magu</p>

        <div className={styles.grid}>
          <a href="/quemsomos" className={styles.card}>
            <h2>Quem somos &rarr;</h2>
            <p>conheça nosso trabalho seja um de nossos parceiros!!</p>
          </a>

          <a href="/contato" className={styles.card}>
            <h2>Contatos &rarr;</h2>
            <p>Entre em contato com o nosso pessoal</p>
          </a>

          <a
            href="/doacoes"
            className={styles.card}
          >
            <h2>Doaçoes &rarr;</h2>
            <p>Seja doador de uma de nossas campanhas</p>
          </a>

          <a
            href="/apoio"
            className={styles.card}
          >
            <h2>Apoio &rarr;</h2>
            <p>
              conheça nossa rede de apoiadores e empresas que se preocupam com o meio ambiente.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          infinitspacedev{' '}
          <span className={styles.logo}>
            
          </span>
        </a>
      </footer>
    </div>
  )
}
